/**
 * Generates random numbers
 */
public class NumberGenerator {

    /**
     * Generates n random numbers between min and max (inclusive).
     * There is a 50/50 chance that the number will be an integer or a double.
     * @param n number of random numbers
     * @param min minimum value
     * @param max maximum value
     * @return array of random numbers
     */
    public static double[] generate(int n, double min, double max) {
        double[] numbers = new double[n];
        for (int i = 0; i < n; i++) {
            double number = Math.random() * (max - min) + min;
            if (Math.random() < 0.5) {
                number = Math.round(number);
            }
            numbers[i] = number;
        }
        return numbers;
    }

    /**
     * Prints the numbers generated by the generate method.
     */
    public static void printNumbers(int n, double min, double max) {
        double[] numbers = generate(n, min, max);
        for (int i = 0; i < n; i++) {
            if (numbers[i] == (int)(numbers[i])) {
                System.out.println((int)numbers[i]);
            } else {
                System.out.println(numbers[i]);
            }
        }
    }

    public static void main(String[] args) {
        int n = Integer.parseInt(args[0]);
        double min = Double.parseDouble(args[1]);
        double max = Double.parseDouble(args[2]);
        printNumbers(n, min, max);
        // printNumbers(20, 0, 10);
    
    }
}
